# -*- mode: ruby -*-
# vi: set ft=ruby :

box = "ubuntu/bionic64"

Vagrant.configure("2") do |config|
  config.vm.box = box

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 1
  end


  config.vm.define "webapp1" do |webapp1|

    webapp1.vm.network "private_network", ip: "192.168.10.1"

    webapp1.vm.provision "shell", inline: <<-SHELL
    set -e
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y --no-install-recommends ansible git

    GITDIR="${HOME}/isucon10-qualify"
    rm -rf ${GITDIR}
    git clone https://github.com/isucon/isucon10-qualify.git ${GITDIR}
    (
      cd ${GITDIR}/provisioning/ansible
      PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i allinone, --connection=local allinone.yaml
    )
    rm -rf ${GITDIR}
    SHELL
  end

  config.vm.define "webapp2" do |webapp2|

    webapp2.vm.network "private_network", ip: "192.168.10.2"

    webapp2.vm.provision "shell", inline: <<-SHELL
    set -e
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y --no-install-recommends ansible git

    GITDIR="${HOME}/isucon10-qualify"
    rm -rf ${GITDIR}
    git clone https://github.com/isucon/isucon10-qualify.git ${GITDIR}
    (
      cd ${GITDIR}/provisioning/ansible
      PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i allinone, --connection=local allinone.yaml
    )
    rm -rf ${GITDIR}
    SHELL
  end
  config.vm.define "webapp3" do |webapp3|

    webapp3.vm.network "private_network", ip: "192.168.10.3"

    webapp3.vm.provision "shell", inline: <<-SHELL
    set -e
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y --no-install-recommends ansible git

    GITDIR="${HOME}/isucon10-qualify"
    rm -rf ${GITDIR}
    git clone https://github.com/isucon/isucon10-qualify.git ${GITDIR}
    (
      cd ${GITDIR}/provisioning/ansible
      PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i allinone, --connection=local allinone.yaml
    )
    rm -rf ${GITDIR}
    SHELL
  end

  config.vm.define "bench" do |bench|

      bench.vm.network "private_network", ip: "192.168.10.4"

      bench.vm.provision "shell", inline: <<-SHELL
    set -e
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y --no-install-recommends ansible git

    GITDIR="${HOME}/isucon10-qualify"
    rm -rf ${GITDIR}
    git clone https://github.com/isucon/isucon10-qualify.git ${GITDIR}
    (
      cd ${GITDIR}/provisioning/ansible
      PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i allinone, --connection=local allinone.yaml
    )
    rm -rf ${GITDIR}
      SHELL
  end
end
